#!/bin/bash
psql -q \
-h "$POSTGRES_HOST" \
-U "$POSTGRES_USER" \
-W "$POSTGRES_PASSWORD" \
-p "$POSTGRES_PORT" \
-d "$POSTGRES_DB" \
-f /mapbender/resources/db/pgsql/init.sql && \
-f /mapbender/resources/db/pgsql/pgsql_schema_2.5.sql && \
-f /mapbender/resources/db/pgsql/pgsql_data_2.5.sql && \
-f /mapbender/resources/db/pgsql/pgsql_serial_set_sequences_2.5.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.5_to_2.5.1rc1_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.5.1rc1_to_2.5.1_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.5.1_to_2.6rc1_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.6rc1_to_2.6_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.6_to_2.6.1_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.6.1_to_2.6.2_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.6.2_to_2.7rc1_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.7rc1_to_2.7rc2_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.7.1_to_2.7.2_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.7.2_to_2.7.3_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.7.3_to_2.7.4_pgsql_UTF-8.sql && \
-f /mapbender/resources/db/pgsql/UTF-8/update/update_2.8_pgsql_UTF-8.sql