INSERT INTO gui (gui_id, gui_name, gui_description, gui_public) VALUES ('template_jquery_ui','template_jquery_ui','elements with Jquery',1);
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','addWMS',2,0,'add a WMS to the running application','Adding WMS','img','../img/button_blue_red/add_off.png','',410,10,28,28,3,'filter:Chroma(color=#C2CBCF);','','img','mod_addWMS.php','mod_addWMSgeneralFunctions.js','treeGDE,mapframe1','loadData','http://www.mapbender.org/index.php/AddWMS');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','body',1,1,'body
(obligatory)','','body','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','','body','','','','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','description',1,1,'','Description','div','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','This application shows some jQuery UI components which are now being used by Mapbender application elements.
<br><br>
Currently there is a only a slider, an accordion and some effects. This application will contain some more items, featuring UI dialogs or the jQuery datatables plugin.
<br><br>
The application is also themed by the jQuery UI CSS framework. Click ''Custom theme'' to start the jQuery UI Themeroller (Firefox only).','div','','','','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','doubleclickZoom',2,1,'adds doubleclick zoom to map module (target).
Deactivates the browser contextmenu!!!','Doubleclick zoom','div','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','','div','mod_doubleclickZoom.js','','mapframe1','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','i18n',1,1,'Internationalization module, collects data from all elements and sends them to the server in a single POST request. The strings are translated via gettext only.','Internationalization','div','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','','div','../plugins/mb_i18n.js','','','','http://www.mapbender.org/Gettext');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','jq_ui',1,1,'The jQuery UI core','','','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','','','','../extensions/jquery-ui-1.7.2.custom/development-bundle/ui/min.ui.core.js','','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','jq_ui_accordion',2,1,'accordion from the jQuery UI framework','','','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','','','','../extensions/jquery-ui-1.7.2.custom/development-bundle/ui/ui.accordion.js','','jq_ui','http://docs.jquery.com/UI/Accordion');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','jq_ui_dialog',5,0,'Module to manage jQuery UI dialog windows with multiple options for customization.','','div','','',-1,-1,NULL ,NULL ,NULL ,'','','div','','../extensions/jquery-ui-1.7.2.custom/development-bundle/ui/min.ui.dialog.js','','jq_ui','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','jq_ui_logo',2,1,'Logo','jQuery UI Logo','img','../img/jquery_ui_logo.png','',35,15,NULL ,NULL ,5,'','','','','','','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','jq_ui_slider',5,1,'slider from the jQuery UI framework','','','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','','','','../extensions/jquery-ui-1.7.2.custom/development-bundle/ui/min.ui.slider.js','','jq_ui','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','jq_ui_themeroller',1,1,'','Themeroller','a','','class=''ui-state-default ui-corner-all'' 
href="javascript:(function(){if%20(!/Firefox/.test(navigator.userAgent)){alert(navigator.userAgent);%20return%20false;%20};%20if(window.jquitr){%20jquitr.addThemeRoller();%20}%20else{%20jquitr%20=%20{};%20jquitr.s%20=%20document.createElement(''script'');%20jquitr.s.src%20=%20''http://jqueryui.com/themeroller/developertool/developertool.js.php'';%20document.getElementsByTagName(''head'')[0].appendChild(jquitr.s);}%20})();"',320,15,NULL ,NULL ,NULL ,'text-decoration:none;padding:0.4em 1em 0.4em 20px','Custom theme','a','','','','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','logo',2,1,'Logo','Logo','img','../img/mapbender_logo_transparent.png','',55,90,NULL ,NULL ,5,'','','','','','','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','mapframe1',1,1,'frame for a map','','div','','class=''ui-corner-all''',320,60,608,467,2,'overflow:hidden;background-color:#ffffff','','div','../plugins/mb_map.js','../../lib/history.js,map_obj.js,map.js,wms.js,wfs_obj.js,initWms.php','','','http://www.mapbender.org/index.php/Mapframe');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','mb_navigation',2,1,'Adds navigation arrows on top of the map','Navigation','div','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','','div','../plugins/mb_navigation.js','','mapframe1','mapframe1','http://www.mapbender.org/Navigation');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','mousewheelZoom',2,1,'adds mousewheel zoom to map module (target)','Mousewheel zoom','div','','',NULL ,NULL ,NULL ,NULL ,NULL ,'','','div','mod_mousewheelZoom.js','../extensions/jquery.mousewheel.min.js','mapframe1','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','overview',2,1,'OverviewFrame','','div','','',320,60,150,130,100,'overflow:hidden;background-color:#ffffff','<div id="overview_maps" style="position:absolute;left:0px;right:0px;"></div>','div','../plugins/mb_overview.js','../../lib/history.js,map_obj.js,map.js,wms.js,wfs_obj.js,initWms.php','mapframe1','mapframe1','http://www.mapbender.org/index.php/Overview');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','overviewToggle',5,1,'','','div','','class="ui-widget-header ui-corner-all" ',-1,-1,NULL ,NULL ,NULL ,'display:none;height:24px;width:35px;vertical-align: middle','<img style=''position:absolute;top:0px;left:0px'' src=''../img/ovtoggle.png'' /><span style=''margin-left: auto; margin-right: 0pt;'' class=''ui-icon ui-icon-triangle-1-e''></span>','div','../javascripts/mod_overviewToggle.js','','overview','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','pan1',2,1,'pan','Pan','img','../img/button_blue_red/pan_off.png','',560,20,28,28,3,'','','img','mod_pan.js','','mapframe1','','http://www.mapbender.org/index.php/Pan');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','resizeMapsize',2,1,'resize mapsize to browser window size','Resize Mapsize','img','../img/button_blink_red/resizemapsize_off.png','',838,10,24,24,NULL ,'filter:Chroma(color=#C2CBCF);visibility:hidden','','img','mod_resize_mapsize.js','','mapframe1','','http://www.mapbender.org/index.php/ResizeMapsize');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','sandclock',2,1,'displays a sand clock while waiting for requests','','div','','',80,0,NULL ,NULL ,NULL ,'','','div','mod_sandclock.js','','mapframe1','','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','selArea1',2,1,'zoombox','Zoom by rectangle','img','../img/button_blue_red/selArea_off.png','',530,20,28,28,1,'','','img','mod_selArea.js','mod_box1.js','mapframe1','','http://www.mapbender.org/index.php/SelArea1');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','tabs_vertical',2,1,'An accordion decorator, replaces the deprecated element tabs','','div','','',10,130,300,NULL ,2,'','','div','../plugins/mb_tabs_vertical.js','','treeGDE,description','jq_ui_accordion','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','treeGDE',2,1,'new treegde2 - directory tree, checkbox for visible, checkbox for querylayer
for more infos have a look at http://www.mapbender.org/index.php/TreeGDE2','Maps','div','','onmouseover="this.style.zIndex=300;this.style.width=350;" onmouseout="this.style.zIndex=2;this.style.width=200"',NULL ,NULL ,250,250,NULL ,'visibility:visible;overflow:scroll','','div','../html/mod_treefolderPlain.php','jsTree.js','mapframe1','mapframe1','http://www.mapbender.org/index.php/TreeGde');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','WMS_preferences',2,0,'configures the preferences of each loaded wms','WMS preferences','img','../img/button_blue/preferences_off.png','onclick=''window.open("../php/mod_WMSpreferences.php?sessionID","","width=400, height=600, left=300, resizable=yes, scrollbars=yes")''  onmouseover=''this.src = this.src.replace(/_off/,"_over");''  onmouseout=''this.src = this.src.replace(/_over/, "_off");''',440,10,28,28,3,'filter:Chroma(color=#C2CBCF);','','img','','','mapframe1,treeGDE','','http://www.mapbender.org/index.php/WMS_preferences');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','wmsTimeSliderYear',5,1,'sets the TIME parameter for all activated WMS (years only)','Time','div','','',700,15,200,50,NULL ,'','','div','../plugins/mb_wmsTimeSliderYear.js','','mapframe1','jq_ui_slider','');
INSERT INTO gui_element (fkey_gui_id, e_id, e_pos, e_public, e_comment, e_title, e_element,e_src, e_attributes, e_left, e_top, e_width, e_height, e_z_index, e_more_styles, e_content, e_closetag, e_js_file, e_mb_mod, e_target, e_requires,e_url) VALUES ('template_jquery_ui','zoomFull',2,1,'zoom to full extent button','Display complete map','img','../img/button_blue_red/zoomFull_off.png','',590,20,24,24,2,'','','img','mod_zoomFull.js','','mapframe1','','http://www.mapbender.org/index.php/ZoomFull');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'body', 'css4TreeGDE', '../css/treeGDE2.css', '', 'file/css');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'body', 'favicon', '../img/favicon.png', 'favicon', 'php_var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'body', 'includeWhileLoading', '../include/preliminary_logo_splash.php', '', 'php_var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'body', 'jquery_css', '../extensions/jquery-ui-1.7.2.custom/css/ui-lightblue/jquery-ui-1.7.2.custom.css', '', 'file/css');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'body', 'jq_ui_theme', '../extensions/jquery-ui-1.7.2.custom/css/smoothness/jquery-ui-1.7.2.custom.css', 'UI Theme from Themeroller', 'file/css');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'body', 'popupcss', '../css/popup.css', 'file css', 'file/css');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'body', 'tablesortercss', '../css/tablesorter.css', 'file css', 'file/css');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'body', 'use_load_message', 'true', '', 'php_var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'jq_ui', 'css', '../extensions/jquery-ui-1.7.2.custom/css/ui-lightness/jquery-ui-1.7.2.custom.css', '', 'file/css');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'jq_ui_accordion', 'active', '2', '', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'mapframe1', 'skipWmsIfSrsNotSupported', '0', 'if set to 1, it skips the WMS request if the current SRS is not supported by the WMS; if set to 0, the WMS is always queried. Default is 0, because of backwards compatibility', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'mapframe1', 'slippy', '1', '1 = Activates an animated, pseudo slippy map', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'mousewheelZoom', 'factor', '2', 'The factor by which the map is zoomed on each mousewheel unit', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'overview', 'overview_wms', '0', 'wms that shows up as overview', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'overview', 'skipWmsIfSrsNotSupported', '0', 'if set to 1, it skips the WMS request if the current SRS is not supported by the WMS; if set to 0, the WMS is always queried. Default is 0, because of backwards compatibility', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'resizeMapsize', 'adjust_height', '-15', 'to adjust the height of the mapframe on the bottom of the window', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'resizeMapsize', 'adjust_width', '-15', 'to adjust the width of the mapframe on the right side of the window', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'resizeMapsize', 'resize_option', 'auto', 'auto (autoresize on load), button (resize by button)', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'sandclock', 'mod_sandclock_image', '../img/loader_lightblue.gif', 'define a sandclock image ', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'tabs_vertical', 'active', '2', '', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'alerterror', 'true', 'alertbox for wms loading error', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'ficheckbox', 'true', 'checkbox for featureInfo requests', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'imagedir', '../img/tree_new', 'image directory', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'menu', 'opacity_up,opacity_down,zoom,metainfo,hide,wms_up,wms_down,layer_up,layer_down,remove', 'context menu elements', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'metadatalink', 'false', 'link for layer-metadata', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'openfolder', 'false', 'initial open folder', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'showstatus', 'true', 'show status in folderimages', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'switchwms', 'true', 'enables/disables all layer of a wms', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'treeGDE', 'wmsbuttons', 'false', 'wms management buttons', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'wmsTimeSliderYear', 'wms', '915', '', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'wmsTimeSliderYear', 'yearDefault', '2007', 'default slider setting', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'wmsTimeSliderYear', 'yearMax', '2007', 'upper end of the time interval', 'var');
INSERT INTO gui_element_vars(fkey_gui_id, fkey_e_id, var_name, var_value, context, var_type) VALUES ('template_jquery_ui', 'wmsTimeSliderYear', 'yearMin', '1995', 'lower end of the time interval', 'var');

INSERT into gui_mb_user (fkey_gui_id , fkey_mb_user_id , mb_user_type) VALUES ('template_jquery_ui',1,'owner');
