jquery_lang_js.prototype.lang.en = {
	//Map
	'(C) Geobasidaten: LvermGeo Rlp 2012':'(C) Base Geodata: LvermGeo Rlp 2012',
	'Karte':'Map',
	//Ebenensteuerung
	'Ebenen':'Layer',
	'Hinweis: Um eine Ebene abzufragen aktivieren Sie die Info-Option und tapen danach in der Karte auf das Objekt der Ebene.':'Note: To query a layer select the Info option and then tap on the object of the layer.',
	'Änderung der Ebenen wechselt direkt zur Kartenansicht':'Changes of layers activate directly mapview',
	
	//Ebenen
	'Hintergrundkarte':'Backgroundmap',
	'Topogr. Karte grau':'Topogr. map grey',
	'Topogr. Karte farbe':'Topogr. map color',
	'Luftbilder':'Aerial photos',
	'keine Hintergrundkarte':'No backgroundmap',	
	'Schutzgebiete':'Protected Areas',
	'Naturschutzgebiete':'Nature Reserves',
	'Landschaftsschutzgebiete':'Conservation Areas',
	'Naturparke':'Nature Parks',
	'Natura 2000 Gebiete':'Natura 2000 Areas',
	'Vogelschutzgebiete':'Birds Directive Site',
	'FFH-Gebiete':'Habitats Directive Site',
	'Biotopkataster':'Habitat Cadastral',
	'Biotoptypen BT Flächen':'Habitat BT Polygons',
	'Biotoptypen BT Linien':'Habitat BT Lines',
	'Biotoptypen BT Punkte':'Habitat BT Points',
	'Biotope BK Flächen':'Habitat BK Polygons',
	'Biotope BK Linien':'Habitat BK Lines',
	'Biotope BK Punkte':'Habitat BK Points',
	'FFH-Lebensraumtypen':'FFH Habitat Types',
	'Artendaten':'Species Data',
	'Artenraster (2x2km)':'Species Raster (2x2km)',
	'Grenzen':'Borders',
	'Liegenschaftskataster':'Cadastral parcel',
	'Kreis Grenzen':'District Boundaries',
	'Vg Grenzen':'Vg Boundaries',
	'Gemeindegrenzen':'Municipal Boundaries',
	'Abfrage Höhe + GPS':'Query Altitude + GPS',	
	
	//Suchseite
	'Suche':'Search',
	'Straße suchen:':'Street search:',
	'Ort suchen:':'Place search:',
	'Suchen':'Search',
	'Suchergebnisse':'Search results',
	'Hausnummern':'House numbers',
	'Zu viele Datensätze! Bitte schränken Sie Ihre Suche ein!':'Too many records! Please narrow your search!',	
	
	//Hilfeseite + Einstellungen
	'Hilfe / Info':'Help / Info',
	'App Einstellungen':'App settings',
	'Einstellungen':'Settings',
	'Sprache:':'Language:',
	'Händigkeit:':'Handedness',
	'Rechtshänder':'Right-handed',
	'Linkshänder':'Left-handed',
	
	//Ajax, JS-Aufrufe ect.
	'Meldung:':'Message:',
	'bitte warten...':'please wait...',
	'Zoom auf Ergebnis in Karte':'Zoom to result on map',
	'Suchergebnis: ':'Search result: ',
	'Positionsgenauigkeit:':'Positional accuracy:',
	'Standardabfrage:':'Standard query:',
	'Koordinaten + Hoehe':'Coordinates + altitude',
	'aktuelle Abfrageebene:':'actual querylayer:',
	'Kein Ergebnis!':'No result!',
	'Abfrageergebnis:':'Query result:',
	'Die ermittelte Position liegt außerhalb des darstellbaren Kartenausschnitts!':'The calculated position is outside the representable map section!',
	'Messen':'Measure',
	'Entfernung: ':'Distance: ',
	'Fläche: ':'Area: ',
	'Entfernungsmessung aktiv!':'Distance measurement active!',
	'Flächenmessung aktiv!':'Area measurement active!',	
	
}